name: Windows Build Tests

on:
  push:
    branches-ignore:
      - master
      - release
      - gha
      - Qt4
      - Qt4-dev
    tags-ignore:
  pull_request:

env:
  QT_VERSION: 5.14.1
  QT_PACKAGES: qtwebengine
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    #continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name:  "Cmake : Qt5 + WebEngine",
            os:    windows-latest,
            setup: "cmake -DUSE_STATIC_CHMLIB=ON -DUSE_WEBENGINE=ON .",
            build: "cmake --build . --config Release",
            install: "cmake --install . --config Release"
          }
        - {
            name:  "qmake : Qt5 + WebEngine",
            os:    windows-latest,
            setup: 'qmake -r "USE_STATIC_CHMLIB=1" "USE_WEBENGINE=1" "LIBZIP_ROOT=C:/Program Files (x86)/libzip"',
            build:  "nmake",
            install: "echo skip"
          }

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt
      uses: jurplel/install-qt-action@v2 # Fuck!!! .7.2
      with:
        version:  ${{ env.QT_VERSION }}
        modules: ${{ env.QT_PACKAGES }}

    - name: Build & install zlib
      shell: bash
      run: |
        cd ../
        git clone https://github.com/madler/zlib.git
        cd zlib
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install . --config Release

    - name: Build & install libzip
      shell: bash
      run: |
        cd ../
        git clone https://github.com/nih-at/libzip.git
        cd libzip
        git checkout v1.7.3
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install . --config Release

    - name: Setup project
      run: ${{ matrix.config.setup }}

    - name: Build project
      run: ${{ matrix.config.build }}
      
    - name: Install project
      shell: bash
      run: ${{ matrix.config.install }}
